name: Create Release Keystore

on:
  workflow_dispatch:

jobs:
  keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Generate keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore blixbloxcatz-release.jks \
            -alias blixbloxcatz \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "#43pfn0fy8j#" \
            -keypass "#43pfn0fy8j#" \
            -dname "CN=BlixBloxCatz, OU=Game, O=BlixBloxCatz, L=Unknown, S=Unknown, C=IN"

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: blixbloxcatz-keystore
          path: blixbloxcatz-release.jks
